
resources:
  - name: rsc-git
    type: git
    source:
      uri: https://github.com/moonii/pub.git
      branch: master
  - name: pub-timer
    type: time
    source:
      interval: 60s


jobs:

  - name: mv-package
    plan:
    - aggregate:
      - get: rsc-git
        trigger: true
      - get: pub-timer

    - task: exe-sh
      privileged: true
      file: rsc-git/pipeline/exe-sh.yml

    - task: mv-package
      privileged: true
      file: rsc-git/pipeline/maven-package.yml

    - task: rename-file
      privileged: true
      file: rsc-git/pipeline/rename-file.yml

