
resources:
  - name: rsc-git
    type: git
    source:
      uri: https://github.com/moonii/pub.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s


jobs:
  - name: mv-package
    plan:
    - aggregate:
      - get: rsc-git
        trigger: true
      - get: time
    - task: mv-package
      privileged: true
      file: rsc-git/pipeline/maven-package.yml
    - task: rename-file
      file: rsc-git/pipeline/rename-file.yml

#   - name: rename file
#     plan:
#     - aggregate:
#       - get: jar-file
#         trigger: true
#         passed: [maven-package]
#       - get: time
#     - task: rename-file
#       file: rsc-git/pipeline/rename-file.yml
